/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type MoneyRequestId = string;
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Transaction {
    id: string;
    status: TransactionStatus;
    recipientAccountNumber: AccountNumber;
    paystackReference: string;
    paystackStatus: string;
    sender: Principal;
    narration: string;
    timestamp: bigint;
    recipientAccountName: string;
    recipientBank: BankName;
    amount: bigint;
}
export type PhoneNumber = string;
export type BankName = string;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface MoneyRequest {
    id: MoneyRequestId;
    status: MoneyRequestStatus;
    requester: Principal;
    bank: BankName;
    accountName: string;
    amountNeeded: bigint;
    timestamp: Timestamp;
    requesterEmail?: string;
    accountNumber: AccountNumber;
    reason: string;
}
export type AccountNumber = string;
export type DeviceType = string;
export interface UserProfile {
    principal: string;
    emailVerified: boolean;
    displayName: string;
    identityAnchor: bigint;
    password: string;
    email: string;
    lastLoginTimestamp: bigint;
    registrationTimestamp: bigint;
    deviceType: string;
    phoneNumber: string;
    phoneVerified: boolean;
}
export type OtpCode = string;
export enum MoneyRequestStatus {
    pending = "pending",
    fulfilled = "fulfilled"
}
export enum TransactionStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminApproveTransaction(transactionId: string): Promise<boolean>;
    adminFulfillMoneyRequest(requestId: MoneyRequestId): Promise<boolean>;
    adminGetAllMoneyRequests(): Promise<Array<MoneyRequest>>;
    adminGetAllProfiles(token: string): Promise<Array<UserProfile>>;
    adminGetAllProfilesAsAdmin(): Promise<Array<UserProfile>>;
    adminGetAllTransactions(): Promise<Array<Transaction>>;
    adminLogin(email: string, password: string): Promise<boolean>;
    adminSendMoneyOnBehalf(recipientBank: BankName, accountNumber: AccountNumber, accountName: string, amount: bigint, narration: string): Promise<Transaction>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    generateOtp(phoneNumber: PhoneNumber): Promise<OtpCode>;
    getBankAccountName(_email: string, bank: BankName, accountNumber: AccountNumber): Promise<string>;
    getBankList(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPaystackSecretKey(): Promise<string>;
    getTransactionHistory(user: Principal): Promise<Array<Transaction>>;
    getUserMoneyRequests(user: Principal): Promise<Array<MoneyRequest>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    loginWithEmail(email: string, password: string): Promise<UserProfile | null>;
    recordLogin(deviceType: DeviceType): Promise<void>;
    recordLoginByEmail(email: string, deviceType: string): Promise<void>;
    registerUserProfile(displayName: string, phoneNumber: string, identityAnchor: bigint, email: string, password: string, deviceType: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveProfile(displayName: string, phoneNumber: string, identityAnchor: bigint, email: string, password: string, emailVerified: boolean): Promise<void>;
    setPaystackSecretKey(secret: string): Promise<void>;
    submitMoneyRequest(reason: string, bank: string, accountNumber: string, accountName: string, amountNeeded: bigint, email: string): Promise<string>;
    transferMoney(recipientAccountNumber: AccountNumber, recipientBank: BankName, recipientAccountName: string, amount: bigint, narration: string): Promise<Transaction>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    verifyOtp(phoneNumber: PhoneNumber, code: OtpCode): Promise<boolean>;
}
import type { AccountNumber as _AccountNumber, BankName as _BankName, MoneyRequest as _MoneyRequest, MoneyRequestId as _MoneyRequestId, MoneyRequestStatus as _MoneyRequestStatus, Timestamp as _Timestamp, Transaction as _Transaction, TransactionStatus as _TransactionStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminApproveTransaction(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveTransaction(arg0);
            return result;
        }
    }
    async adminFulfillMoneyRequest(arg0: MoneyRequestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminFulfillMoneyRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminFulfillMoneyRequest(arg0);
            return result;
        }
    }
    async adminGetAllMoneyRequests(): Promise<Array<MoneyRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllMoneyRequests();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllMoneyRequests();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllProfiles(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllProfiles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllProfiles(arg0);
            return result;
        }
    }
    async adminGetAllProfilesAsAdmin(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllProfilesAsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllProfilesAsAdmin();
            return result;
        }
    }
    async adminGetAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllTransactions();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllTransactions();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async adminSendMoneyOnBehalf(arg0: BankName, arg1: AccountNumber, arg2: string, arg3: bigint, arg4: string): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSendMoneyOnBehalf(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Transaction_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSendMoneyOnBehalf(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Transaction_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async generateOtp(arg0: PhoneNumber): Promise<OtpCode> {
        if (this.processError) {
            try {
                const result = await this.actor.generateOtp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateOtp(arg0);
            return result;
        }
    }
    async getBankAccountName(arg0: string, arg1: BankName, arg2: AccountNumber): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBankAccountName(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBankAccountName(arg0, arg1, arg2);
            return result;
        }
    }
    async getBankList(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBankList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBankList();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaystackSecretKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaystackSecretKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaystackSecretKey();
            return result;
        }
    }
    async getTransactionHistory(arg0: Principal): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserMoneyRequests(arg0: Principal): Promise<Array<MoneyRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMoneyRequests(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMoneyRequests(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginWithEmail(arg0: string, arg1: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithEmail(arg0, arg1);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithEmail(arg0, arg1);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordLogin(arg0: DeviceType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordLogin(arg0);
            return result;
        }
    }
    async recordLoginByEmail(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordLoginByEmail(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordLoginByEmail(arg0, arg1);
            return result;
        }
    }
    async registerUserProfile(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUserProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUserProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveProfile(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async setPaystackSecretKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPaystackSecretKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPaystackSecretKey(arg0);
            return result;
        }
    }
    async submitMoneyRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMoneyRequest(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMoneyRequest(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async transferMoney(arg0: AccountNumber, arg1: BankName, arg2: string, arg3: bigint, arg4: string): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.transferMoney(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Transaction_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferMoney(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Transaction_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async verifyOtp(arg0: PhoneNumber, arg1: OtpCode): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOtp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOtp(arg0, arg1);
            return result;
        }
    }
}
function from_candid_MoneyRequestStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoneyRequestStatus): MoneyRequestStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_MoneyRequest_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoneyRequest): MoneyRequest {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MoneyRequestId;
    status: _MoneyRequestStatus;
    requester: Principal;
    bank: _BankName;
    accountName: string;
    amountNeeded: bigint;
    timestamp: _Timestamp;
    requesterEmail: [] | [string];
    accountNumber: _AccountNumber;
    reason: string;
}): {
    id: MoneyRequestId;
    status: MoneyRequestStatus;
    requester: Principal;
    bank: BankName;
    accountName: string;
    amountNeeded: bigint;
    timestamp: Timestamp;
    requesterEmail?: string;
    accountNumber: AccountNumber;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_MoneyRequestStatus_n4(_uploadFile, _downloadFile, value.status),
        requester: value.requester,
        bank: value.bank,
        accountName: value.accountName,
        amountNeeded: value.amountNeeded,
        timestamp: value.timestamp,
        requesterEmail: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.requesterEmail)),
        accountNumber: value.accountNumber,
        reason: value.reason
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TransactionStatus;
    recipientAccountNumber: _AccountNumber;
    paystackReference: string;
    paystackStatus: string;
    sender: Principal;
    narration: string;
    timestamp: bigint;
    recipientAccountName: string;
    recipientBank: _BankName;
    amount: bigint;
}): {
    id: string;
    status: TransactionStatus;
    recipientAccountNumber: AccountNumber;
    paystackReference: string;
    paystackStatus: string;
    sender: Principal;
    narration: string;
    timestamp: bigint;
    recipientAccountName: string;
    recipientBank: BankName;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n10(_uploadFile, _downloadFile, value.status),
        recipientAccountNumber: value.recipientAccountNumber,
        paystackReference: value.paystackReference,
        paystackStatus: value.paystackStatus,
        sender: value.sender,
        narration: value.narration,
        timestamp: value.timestamp,
        recipientAccountName: value.recipientAccountName,
        recipientBank: value.recipientBank,
        amount: value.amount
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "completed" in value ? TransactionStatus.completed : "failed" in value ? TransactionStatus.failed : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    fulfilled: null;
}): MoneyRequestStatus {
    return "pending" in value ? MoneyRequestStatus.pending : "fulfilled" in value ? MoneyRequestStatus.fulfilled : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MoneyRequest>): Array<MoneyRequest> {
    return value.map((x)=>from_candid_MoneyRequest_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n8(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
