/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountNumber = string;
export type BankName = string;
export type DeviceType = string;
export interface MoneyRequest {
  'id' : MoneyRequestId,
  'status' : MoneyRequestStatus,
  'requester' : Principal,
  'bank' : BankName,
  'accountName' : string,
  'amountNeeded' : bigint,
  'timestamp' : Timestamp,
  'requesterEmail' : [] | [string],
  'accountNumber' : AccountNumber,
  'reason' : string,
}
export type MoneyRequestId = string;
export type MoneyRequestStatus = { 'pending' : null } |
  { 'fulfilled' : null };
export type OtpCode = string;
export type PhoneNumber = string;
export type Timestamp = bigint;
export interface Transaction {
  'id' : string,
  'status' : TransactionStatus,
  'recipientAccountNumber' : AccountNumber,
  'paystackReference' : string,
  'paystackStatus' : string,
  'sender' : Principal,
  'narration' : string,
  'timestamp' : bigint,
  'recipientAccountName' : string,
  'recipientBank' : BankName,
  'amount' : bigint,
}
export type TransactionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'principal' : string,
  'emailVerified' : boolean,
  'displayName' : string,
  'identityAnchor' : bigint,
  'password' : string,
  'email' : string,
  'lastLoginTimestamp' : bigint,
  'registrationTimestamp' : bigint,
  'deviceType' : string,
  'phoneNumber' : string,
  'phoneVerified' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminApproveTransaction' : ActorMethod<[string], boolean>,
  'adminFulfillMoneyRequest' : ActorMethod<[MoneyRequestId], boolean>,
  'adminGetAllMoneyRequests' : ActorMethod<[], Array<MoneyRequest>>,
  'adminGetAllProfiles' : ActorMethod<[string], Array<UserProfile>>,
  'adminGetAllProfilesAsAdmin' : ActorMethod<[], Array<UserProfile>>,
  'adminGetAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'adminSendMoneyOnBehalf' : ActorMethod<
    [BankName, AccountNumber, string, bigint, string],
    Transaction
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateOtp' : ActorMethod<[PhoneNumber], OtpCode>,
  'getBankAccountName' : ActorMethod<[string, BankName, AccountNumber], string>,
  'getBankList' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPaystackSecretKey' : ActorMethod<[], string>,
  'getTransactionHistory' : ActorMethod<[Principal], Array<Transaction>>,
  'getUserMoneyRequests' : ActorMethod<[Principal], Array<MoneyRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginWithEmail' : ActorMethod<[string, string], [] | [UserProfile]>,
  'recordLogin' : ActorMethod<[DeviceType], undefined>,
  'recordLoginByEmail' : ActorMethod<[string, string], undefined>,
  'registerUserProfile' : ActorMethod<
    [string, string, bigint, string, string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProfile' : ActorMethod<
    [string, string, bigint, string, string, boolean],
    undefined
  >,
  'setPaystackSecretKey' : ActorMethod<[string], undefined>,
  'submitMoneyRequest' : ActorMethod<
    [string, string, string, string, bigint, string],
    string
  >,
  'transferMoney' : ActorMethod<
    [AccountNumber, BankName, string, bigint, string],
    Transaction
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'verifyOtp' : ActorMethod<[PhoneNumber, OtpCode], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];