/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MoneyRequestId = IDL.Text;
export const MoneyRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'fulfilled' : IDL.Null,
});
export const BankName = IDL.Text;
export const Timestamp = IDL.Int;
export const AccountNumber = IDL.Text;
export const MoneyRequest = IDL.Record({
  'id' : MoneyRequestId,
  'status' : MoneyRequestStatus,
  'requester' : IDL.Principal,
  'bank' : BankName,
  'accountName' : IDL.Text,
  'amountNeeded' : IDL.Nat,
  'timestamp' : Timestamp,
  'requesterEmail' : IDL.Opt(IDL.Text),
  'accountNumber' : AccountNumber,
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Text,
  'emailVerified' : IDL.Bool,
  'displayName' : IDL.Text,
  'identityAnchor' : IDL.Nat,
  'password' : IDL.Text,
  'email' : IDL.Text,
  'lastLoginTimestamp' : IDL.Int,
  'registrationTimestamp' : IDL.Int,
  'deviceType' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'phoneVerified' : IDL.Bool,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : TransactionStatus,
  'recipientAccountNumber' : AccountNumber,
  'paystackReference' : IDL.Text,
  'paystackStatus' : IDL.Text,
  'sender' : IDL.Principal,
  'narration' : IDL.Text,
  'timestamp' : IDL.Int,
  'recipientAccountName' : IDL.Text,
  'recipientBank' : BankName,
  'amount' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PhoneNumber = IDL.Text;
export const OtpCode = IDL.Text;
export const DeviceType = IDL.Text;
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminApproveTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'adminFulfillMoneyRequest' : IDL.Func([MoneyRequestId], [IDL.Bool], []),
  'adminGetAllMoneyRequests' : IDL.Func([], [IDL.Vec(MoneyRequest)], ['query']),
  'adminGetAllProfiles' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'adminGetAllProfilesAsAdmin' : IDL.Func(
      [],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'adminGetAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminSendMoneyOnBehalf' : IDL.Func(
      [BankName, AccountNumber, IDL.Text, IDL.Nat, IDL.Text],
      [Transaction],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateOtp' : IDL.Func([PhoneNumber], [OtpCode], []),
  'getBankAccountName' : IDL.Func(
      [IDL.Text, BankName, AccountNumber],
      [IDL.Text],
      [],
    ),
  'getBankList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaystackSecretKey' : IDL.Func([], [IDL.Text], ['query']),
  'getTransactionHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserMoneyRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MoneyRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginWithEmail' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(UserProfile)], []),
  'recordLogin' : IDL.Func([DeviceType], [], []),
  'recordLoginByEmail' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'registerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'setPaystackSecretKey' : IDL.Func([IDL.Text], [], []),
  'submitMoneyRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'transferMoney' : IDL.Func(
      [AccountNumber, BankName, IDL.Text, IDL.Int, IDL.Text],
      [Transaction],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'verifyOtp' : IDL.Func([PhoneNumber, OtpCode], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MoneyRequestId = IDL.Text;
  const MoneyRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'fulfilled' : IDL.Null,
  });
  const BankName = IDL.Text;
  const Timestamp = IDL.Int;
  const AccountNumber = IDL.Text;
  const MoneyRequest = IDL.Record({
    'id' : MoneyRequestId,
    'status' : MoneyRequestStatus,
    'requester' : IDL.Principal,
    'bank' : BankName,
    'accountName' : IDL.Text,
    'amountNeeded' : IDL.Nat,
    'timestamp' : Timestamp,
    'requesterEmail' : IDL.Opt(IDL.Text),
    'accountNumber' : AccountNumber,
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Text,
    'emailVerified' : IDL.Bool,
    'displayName' : IDL.Text,
    'identityAnchor' : IDL.Nat,
    'password' : IDL.Text,
    'email' : IDL.Text,
    'lastLoginTimestamp' : IDL.Int,
    'registrationTimestamp' : IDL.Int,
    'deviceType' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'phoneVerified' : IDL.Bool,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : TransactionStatus,
    'recipientAccountNumber' : AccountNumber,
    'paystackReference' : IDL.Text,
    'paystackStatus' : IDL.Text,
    'sender' : IDL.Principal,
    'narration' : IDL.Text,
    'timestamp' : IDL.Int,
    'recipientAccountName' : IDL.Text,
    'recipientBank' : BankName,
    'amount' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PhoneNumber = IDL.Text;
  const OtpCode = IDL.Text;
  const DeviceType = IDL.Text;
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminApproveTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'adminFulfillMoneyRequest' : IDL.Func([MoneyRequestId], [IDL.Bool], []),
    'adminGetAllMoneyRequests' : IDL.Func(
        [],
        [IDL.Vec(MoneyRequest)],
        ['query'],
      ),
    'adminGetAllProfiles' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'adminGetAllProfilesAsAdmin' : IDL.Func(
        [],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'adminGetAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminSendMoneyOnBehalf' : IDL.Func(
        [BankName, AccountNumber, IDL.Text, IDL.Nat, IDL.Text],
        [Transaction],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateOtp' : IDL.Func([PhoneNumber], [OtpCode], []),
    'getBankAccountName' : IDL.Func(
        [IDL.Text, BankName, AccountNumber],
        [IDL.Text],
        [],
      ),
    'getBankList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaystackSecretKey' : IDL.Func([], [IDL.Text], ['query']),
    'getTransactionHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserMoneyRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MoneyRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginWithEmail' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(UserProfile)],
        [],
      ),
    'recordLogin' : IDL.Func([DeviceType], [], []),
    'recordLoginByEmail' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'setPaystackSecretKey' : IDL.Func([IDL.Text], [], []),
    'submitMoneyRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'transferMoney' : IDL.Func(
        [AccountNumber, BankName, IDL.Text, IDL.Int, IDL.Text],
        [Transaction],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'verifyOtp' : IDL.Func([PhoneNumber, OtpCode], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };